// <auto-generated />
namespace PomodoroOrders.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AlterModeloOrden_ModeloCarrito : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterModeloOrden_ModeloCarrito));
        
        string IMigrationMetadata.Id
        {
            get { return "201507102302374_AlterModeloOrden_ModeloCarrito"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
